- name: Hacer ping
  ansible.builtin.ping:

- name: Set timezone to Europe/Madrid
  community.general.timezone:
    name: Europe/Madrid

- name: Instalar chrony
  ansible.builtin.package:
    name: chrony
    state: latest

- name: Habilitar chronyd
  systemd:
    name: chronyd
    enabled: yes

- name: Iniciar chronyd
  command: /usr/bin/systemctl start chronyd

# no me funciona la iniciación con modulos de ansible
#- name: Iniciar chronyd
#  systemd: 
#    name: chronyd
#    state: started
#    enabled: yes

- name: Enable ntp
  command: /usr/bin/timedatectl set-ntp true

- name: Deshabilitar SELinux
  command: /usr/bin/sed -i s/=enforcing/=disabled/g /etc/selinux/config

- name: Instalar paquetes
  ansible.builtin.package:
    name: 
      - nfs-utils
      - nfs4-acl-tools
      - wget
    state: latest